# Generated by Django 3.2.9 on 2021-11-05 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastPing', models.DateTimeField(auto_now=True)),
                ('IpAddress', models.TextField(primary_key=True, serialize=False)),
                ('nickName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastPing', models.DateTimeField(auto_now=True)),
                ('fileName', models.CharField(max_length=100)),
                ('filePath', models.CharField(max_length=200)),
                ('Node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.node')),
            ],
        ),
    ]
